version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/.gradle:/root/.gradle
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/roommate
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    command: ["./gradlew", "bootRun", "--continuous"]
    networks:
      - app-network
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=roommate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - app-network
volumes:
  postgres_data:
networks:
  app-network:
